name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.17.0'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_PEM_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to EC2
      env:
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
      run: |
        scp -r -i ~/.ssh/id_rsa * $EC2_USER@$EC2_HOST:/path/to/deployment/directory
        ssh -i ~/.ssh/id_rsa $EC2_USER@$EC2_HOST << 'EOF'
          cd /path/to/deployment/directory
          # Add commands to restart your application/server
          # For example, if using Node.js:
          pm2 restart all
EOF
